name: Codeowner Request 
description: Request required PR review exemption. 
title: "Codeowner access request for [NAME HERE]: "
labels: ["platform-support-ticket"]
assignees:
body:
  - type: input
    id: yourName
    attributes:
      label: Your Name
      description: Please provide the name of the target individual
      placeholder: ex. Jane Doe
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Your Email
      description: Please provide the work email for the target individual
      placeholder: ex. jane.doe@company.com
    validations:
      required: true
  - type: textarea
    id: desiredCodeownerTeams
    attributes:
      label: What teams are you looking to approve PRs for? 
      description: Please list the teams in the box below
      placeholder: "@department-of-veterans-affairs/group"
      value: ""
    validations:
      required: true
  - type: checkboxes
    id: bestPracticeReview
    attributes:
      label: Documentation
      description: I have reviewed the PR best practice documentation.
      options:
        - label: Req
          required: true
