name: Codeowner access request for [NAME]
description: Request required PR review exemption. 
title: "Codeowner access request for [NAME HERE]: "
labels: ["platform-support-ticket"]
body:
  - type: input
    id: yourName
    attributes:
      label: Your Name
      description: Please provide the name of the target individual
      placeholder: ex. Jane Doe
    validations:
      required: true
  - type: input
    id: email
    attributes:
      label: Your Email
      description: Please provide the work email for the target individual
      placeholder: ex. jane.doe@company.com
    validations:
      required: true
  - type: input
    id: GitHubhandle
    attributes:
      label: GitHub handle
      description: Please provide your Github handle.
    validations:
      required: true
  - type: textarea
    id: desiredCodeownerTeams
    attributes:
      label: What teams are you looking to approve PRs for? 
      description: Please list the teams in the box below
      placeholder: "@department-of-veterans-affairs/group"
      value: filler
    validations:
      required: true
  - type: checkboxes
    id: bestPracticeReview
    attributes:
      label: PR Best Practice Documentation Review
      description: I have reviewed the [PR Best Practices](https://depo-platform-documentation.scrollhelp.site/developer-docs/submitting-pull-requests-for-approval).
      options:
        - label: I acknowledge that I have read the above documentation on PR best practices on the va.gov Platform.
          required: true
  - type: markdown
    attributes:
      value: "---"
  - type: checkboxes
    attributes:
      label: Tasks for Platform
      description: The items in this checklist are for Platform to complete. 
      options:
        - label: Support ticket linked below.
        - label: PR for codeowner change linked below. 
