#---
# name: OOB Deploy Request
# about: To request Out of band deployment
# title: OOB Deploy Request
# labels: platform-tech-team-support
# assignees: ''

# ---
name: OOB Deploy Request
description: To request Out of band deployment.
title: "OOB Deploy Request "
labels: ["platform-tech-team-support"]


body:
  - type: markdown
    attributes:
      value: |
        Please fill out the necessary details and list the PRs related to the OOB deployment in the sections below.
  - type: textarea
    id: PR-links
    attributes:
      label: Related PRs
      description: Please provide the list of PRs related to the need for this OOB Deploy
      placeholder: List of PRs
      # value: "- PR Link "
    validations:
      required: true
  - type: dropdown
    id: incidentClassification
    attributes:
      label: Classify Severity of Incident
      description: "What level of severity would you classify this incident? Please refer to our [Platform document on Classifying incidents](https://depo-platform-documentation.scrollhelp.site/support/va-platform-incident-playbook#VAPlatformIncidentPlaybook-ClassifyingtheIncident) for our classification rubric"
      multiple: false
      options:
        - Critical
        - High
        - Moderate
        - Low
    validations:
      required: true
  - type: input
    id: impactedUsers
    attributes:
      label: Active Daily Users Impacted
      description: How many active users are impacted at this time and day. 
    validations:
      required: true
  - type: checkboxes
    id: stagingCheck
    attributes:
      label: Has fix been confirmed in Staging?
#      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com). 
      options:
        - label: Yes
          required: true

      


 ## PRs Related to OOB
# Please provide the list of PRs related to the need for this OOB Deploy below:
# - PR link

## Classify Severity of Incident
# Using this rubric, what level of severity would you classify this incident? For more information, please refer to our Platform document on Classifying incidents. 

# [add rubric]

# Dropdown: 
# - Critical
# - High
# - Moderate
# - Low

## Active Daily Users Impacted
# - How many active users are impacted at this time and day.
  #  >

## Has fix been confirmed in Staging?
# - [ ] Yes
# - [ ] No

### If not confirmed in Staging, why not? 
# [text box] 

## Please list the validation steps to confirm fix
# [text box]

## Who has validated the above?
# [text box]

## Description
# - Please provide the details/reason for the OOB Deploy
#    > Add Details Here ... 
   
## Verify The following
#  - [ ] The OOB Deploy Request is after the cutoff time for the regular deploy.[^1] 
#  - [ ] The OOB Deploy Request is critical and must be resolved before the next automated deploy.
#  - [ ] You are prepared to create an Incident Post Mortem[^2] within two business days.

# [^1]: (See [Deployment Policy](https://depo-platform-documentation.scrollhelp.site/developer-docs/deployment-policies) and [Deployment Schedules](https://depo-platform-documentation.scrollhelp.site/developer-docs/Deployments.1844641889.html)
# [^2]: https://github.com/department-of-veterans-affairs/va.gov-team-sensitive/tree/master/Postmortems


# *Performed by Platform Support Team*
#  - [ ] PagerDuty OOB Deploy Incident Opened
#  - [ ] OCTO-DE staff acknowledgment of Request, via `/pd trigger`
#  - [ ] Notification is posted in the appropriate Slack support and team Channels
#  - [ ] Infrastructure/Operations has acknowledge the Requests (This applies to revproxy and fwdproxy, but is not required for Frontend and Backend requests)
#  - [ ] Security Team has Reviewed the requests (This is not necessary for requests that are not related to security) 
