name: Test Required Fields
description: File a ticket with required fields.
title: "[TEST]: "
labels: ["good first issue", "documentation"]
body:
  - type: markdown
    attributes:
      value: |
        This is a test!
  - type: input
    id: test-input
    attributes:
      label: Test Input Field
      description: Here is a test input field
      placeholder: example placeholder
    validations:
      required: false
  - type: textarea
    id: test-textbox
    attributes:
      label: Test Textbox Field
      description: This is a test textbox
      placeholder: Placeholder!
      value: "Look at this field!"
    validations:
      required: true
  - type: dropdown
    id: test-dropdown
    attributes:
      label: Here is a single choice dropdown
      description: Here is a simple dropdown
      options:
        - Test 1
        - Test 2
        - Test 3
      default: 0
    validations:
      required: false
- type: checkboxes
    id: terms
    attributes:
      label: Secure Passphrase
      options:
        - label: I agree that my Passphrase is strong see [here](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/working-with-ssh-key-passphrases) for more information
          required: true
