name: email
description: Give vagov email.
title: "Email:"
body:
- type: input
  attributes:
    label: VaGovEmail
    description: "What is your va.gov email?"
    placeholder: "firstname.lastname@va.gov"
  value: "@va.gov"
  validations:
    required: true
