
name: Offboarding request
description: To inform the Platform team when a VA.gov Platform or VFS team member has left and needs offboarding.
title: Offboarding of [individual]
labels: analytics-insights, Offboarding, operations

body:
  - type: markdown
    attributes:
      value: "# Instructions"
  - type: markdown
    attributes:
      value: "Fill out name of individual and **Description** section below. Note: This form only handles deactivation from the DSVA (Office of CTO @ VA) Slack instance. For Lighthouse Slack and other DOTS-managed tool removal, please submit a [ticket for DOTS removal](https://jira.devops.va.gov/servicedesk/customer/portal/1/create/714)."
  - type: markdown
    attributes:
      value: "*(Please add only one individual per form)*"
  - type: markdown
    attributes:
      value: "</br></br>"
  - type: markdown
    attributes:
      value: "# Description"
  - type: markdown
    attributes:
      value: "Please provide the following information about the individual being offboarded:"
  - type: input
    id: requiredName
    attributes:
      label: Name
      description:
      placeholder: ex. Jane Smith
    validations:
      required: true
  - type: input
    id: teamName
    attributes:
      label: Team Name
      description:
      placeholder: 
    validations:
      required: true
  - type: input 
    id: teamRole
    attributes:
      label: Role on Team
      description:
      placeholder: 
    validations:
      required: true
  - type: input
    id: lastDay
    attributes:
      label: Expected Last Day
      description: Expected last day in role
      placeholder: MM/DD/YYYY
    validations:
      required: true
  - type: input 
    id: Company
    attributes:
      label: Company they work for
      description:
      placeholder: 
    validations:
      required: true
  - type: input 
    id: email
    attributes:
      label: Email
      description: (Multiple emails listed in order of relevance to VA business, VA, Company, Personal, etc....)
      placeholder: 
    validations:
      required: true
  - type: input 
    id: GithubUsername
    attributes:
      label: GitHub Username
      description: Please include "@" symbol
      placeholder: 
    validations:
      required: true
  - type: input 
    id: userCOR
    attributes:
      label: COR
      description:
      placeholder: 
    validations:
      required: true
  - type: input 
    id: userPM
    attributes:
      label: PM
      description:
      placeholder: 
    validations:
      required: true
  - type: input 
    id: additionalAccess
    attributes:
      label: Additional access
      description: First line formatted with access titles only. 
      placeholder: ex: SOCKS, Pagerduty, Google analytics, etc.
    validations:
      required: true
  - type: textarea
    id: testTextArea
    attributes:
      label: This is a test text area
      description: Now you can type tons of words and stuff
      placeholder: Talk here!
      value: "Talking!"
    validations:
      required: false
  - type: dropdown
    id: testDropdown
    attributes:
      label: Test test
      description: Look at this fancy dropdown
      options:
        - Test 1
        - Test 2
      default: 0
    validations:
      required: false
  - type: dropdown
    id: MCTest
    attributes:
      label: Multiple Choice!
      multiple: true
      options:
        - MC 1
        - MC 2
        - MC 3
  - type: checkboxes
    id: testCheckbox
    attributes:
      label: Test Checkbox
      options:
        - label: I agree that this is a test
          required: true
