name: Test Required Fields
description: File a ticket with required fields.
title: "[TEST]: "
labels: ["good first issue", "documentation"]
body:
  - type: markdown
    attributes:
      value: |
        This is a test!
  - type: checkboxes
    id: test-checkbox
    attributes:
      label: Secure Passphrase
      options:
        - label: I agree that my Passphrase is strong see [here](https://docs.github.com/en/authentication/connecting-to-github-with-ssh/working-with-ssh-key-passphrases) for more information
          required: true
