name: email
description: Give vagov email.
title: "Email:"
labels: ["email"]
body:
- type: input
  id: vagov
  attributes:
    label: VaGovEmail
    description: "What is your va.gov email?"
    placeholder: "firstname.lastname@va.gov"
    value: "@va.gov"
  validations:
    required: true
