
name: Offboarding request
description: To inform the Platform team when a VA.gov Platform or VFS team member has left and needs offboarding.
title: Offboarding of [individual]
labels: analytics-insights, Offboarding, operations

body:
  - type: markdown
    attributes:
      value: "# Instructions"
  - type: markdown
    attributes:
      value: "Fill out name of individual and **Description** section below. Note: This form only handles deactivation from the DSVA (Office of CTO @ VA) Slack instance. For Lighthouse Slack and other DOTS-managed tool removal, please submit a [ticket for DOTS removal](https://jira.devops.va.gov/servicedesk/customer/portal/1/create/714)."
  - type: input
    id: testInput
    attributes:
      label: Test Input Field
      description: Here is a test of an input field
      placeholder: Here is an example placeholder good for examples
    validations:
      required: true
  - type: textarea
    id: testTextArea
    attributes:
      label: This is a test text area
      description: Now you can type tons of words and stuff
      placeholder: Talk here!
      value: "Talking!"
    validations:
      required: false
  - type: dropdown
    id: testDropdown
    attributes:
      label: Test test
      description: Look at this fancy dropdown
      options:
        - Test 1
        - Test 2
      default: 0
    validations:
      required: false
  - type: dropdown
    id: MCTest
    attributes:
      label: Multiple Choice!
      multiple: true
      options:
        - MC 1
        - MC 2
        - MC 3
  - type: checkboxes
    id: testCheckbox
    attributes:
      label: Test Checkbox
      options:
        - label: I agree that this is a test
          required: true
